import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import { Theme } from "@radix-ui/themes";
import { OrderProvider } from "@/contexts/OrderContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="PT-br">
      <body>
        <Theme>
          <OrderProvider>
            {children}
          </OrderProvider>
        </Theme>
      </body>
    </html>
  );
}
